src/tpi/mod.rs

Parentheses after primitive types will be prohibited in the future by rust-lang/rust#42238. This patch will remove the parentheses.

Remove () from usize().

---

src/common.rs
src/dbi.rs
src/lib.rs

I started looking at the code to see if I could replicate the `dump_syms` tool we use, but one of the first things it does is iterate over the modules in the DBI stream. So I implemented that. I don't know if this is the best way to expose this or not, but it works. I compared the output of `llvm-pdbdump raw -modules` (grepped for `Name:`) and a program that is basically the example code I added here and they match exactly.

Add support for reading and iterating over modules from the DBI stream

---

examples/pdb_symbols.rs
src/dbi.rs
src/lib.rs
src/module_info.rs
src/pdb.rs
src/symbol/mod.rs

This patch adds a `PDB::module_info` function to get the module info stream
for a specific module, a new `ModuleInfo` struct to hold that stream's data,
and a `ModuleInfo::symbols` function to get a `SymbolIter` to iterate over
the module's private symbols.
It was also necessary to change `SymbolIter::next` to accept symbols that are
exactly 2 bytes in length, since there are symbols like that in the in-tree
test PDB (S_END, among others).
The pdb_symbols example was also changed to iterate over and print module
private symbols, although that's less useful than one might think because
`Symbol::parse` doesn't support the full set of symbol records that show
up there.
The module information stream also contains line info, so adding support for
that on top of this change should be …

Add support for reading the module information stream for modules, iterating over module private symbols.

---

examples/pdb2hpp.rs
examples/pdb_symbols.rs
src/lib.rs
src/msf/page_list.rs
src/source.rs
src/symbol/mod.rs
src/tpi/data.rs
src/tpi/mod.rs
src/tpi/primitive.rs
tests/symbol_table.rs
tests/type_information.rs

Fixes #1 
I'm not completely convinced this is an improvement, so see what you think. It improves my own code, but I don't think it's improved much of the example code in this crate.
It's added a lot of new exported types, which makes it hard to see the important types in the documentation. Maybe the new types should be kept in submodules? Because I'm lazy, I've switched to using `pub use symbol::*`, along with `pub(crate)` for things that shouldn't be exported. I don't know if this is good style.
Please bikeshed the names. I notice LLVM uses `Record` for its versions of the type records (but not the symbol records).

Add separate structs for enum variants

---

examples/stream_names.rs
src/lib.rs
src/pdb.rs
src/pdbi.rs
tests/pdb_information.rs

I've had most of this sitting around on a branch for a while, I just forgot to finish it off and submit it.
The name stream is contained in the PDB information stream. There are a few streams that need to be looked up by name. Confusingly, one of them is named `/names`. That stream contains source file names, so this will be useful for some future changes I hope to write.
The second changeset here allows access to a raw `Stream` by index. Combined with the first patch this allows looking up a named stream and getting its contents. I don't *love* this change, since the `Stream` + `ParseBuffer` API is a little awkward if you're not trying to parse out data structures. Maybe it would be nicer to add a wrapper struct that just contained an `as_bytes()` method to hide all that?
I wanted that …

Add support for reading stream names, getting raw streams

---

Cargo.lock
Cargo.toml
src/common.rs
src/lib.rs
src/msf/mod.rs

Hey! I got motivated to try out `scroll` so I started taking a crack at fixing https://github.com/willglynn/pdb/issues/10.
This patch only changes over the code in `src/msf/mod.rs`, so it's mostly a wash since that code does a lot of reading individual `u32`s, but it does make reading the PDB header nicer. If you like how this looks I can go through and convert the rest of the crate's I/O to use scroll.
One thought: since we're going to wind up with a bunch of structs that define the on-disk PDB format, should those go in their own module?
cc @m4b

Initial cut at using scroll+scroll_derive

---

examples/pdb_symbols.rs
src/symbol/mod.rs

- Add ProcedureSymbol struct used to hold data for
symbol records with kinds: S_GPROC32, S_GPROC32_ST,
S_LPROC32, S_LPROC32_ST, S_GPROC32_ID, S_LPROC32_ID,
S_LPROC32_DPC, S_LPROC32_DPC_ID. These kinds are
used for module private procedures.
- Add Procedure variant to SymbolData enum
- Add ProcedureFlags struct used to hold data from
a CV_PROCFLAGS bit field. This is used by
ProcedureSymbol
- Add support to pdb_symbols example to print names
of module private procedures
- Add unit tests for parsing a few of the new symbol
kinds, S_LPROC32 and S_GPROC32

Add support for module private procedure symbols

---

Cargo.toml

This reduces the size of the crate from >1mb to 58kB

Exclude fixtures from the packaged crate

---

src/symbol/mod.rs

The length of the symbol only needs to be 2 bytes more than
the length of the field data. The 2 bytes are for the kind.
The first 2 bytes of the symbol containing the length or not
included in the slice of symbol data.

Fix symbol length check.

---

src/symbol/mod.rs

I was running into this not being supported.
This was based on https://github.com/jbevain/cecil/blob/master/symbols/pdb/Microsoft.Cci.Pdb/CvInfo.cs
```
internal struct ObjNameSym {
// internal ushort reclen;    // Record length [SYMTYPE]
// internal ushort rectyp;    // S_OBJNAME
internal uint signature;  // signature
internal string name;       // Length-prefixed name
};
```
Am I right in thinking the two ushort's and the name string are covered automatically by this crate? Leaving this to just be a 4 byte struct with `signature`.

Add support for S_OBJNAME (0x1101)

---

.gitignore
Cargo.lock
Cargo.toml
examples/pdb_symbols.rs
fixtures/symbol_server/README.md
src/common.rs
src/dbi.rs
src/lib.rs
src/msf/mod.rs
src/omap.rs
src/pdb.rs
src/pe.rs
src/symbol/mod.rs
tests/omap_address_translation.rs

This picks up on the work done and discussed at https://github.com/willglynn/pdb/issues/17 and adds the missing `AddressTranslator`.
Additionally, this PR slightly restructures when and how the optional debug header (_"extra streams"_) are read. This is now performed lazily only when needed to speed up parsing of the initial PDB struct. While parsing the optional header is not a ton of work, it's still avoidable if one is only interested in some of the other streams.
There are also a bunch of new public methods on the PDB, namely: `omap_from_src`, `omap_to_src`, `original_sections`. The use of `AddressTranslator` is still preferred, but in case someone wants to use those directly, they get a handle to this. I suppose it might be cleaner to put all these methods in a different place, but …

Implement OMAP-based address translation

---

src/common.rs
src/symbol/mod.rs

As seen here:
https://github.com/Microsoft/microsoft-pdb/blob/master/cvdump/dumpsym7.cpp#L3797
Without this change the name was missing or mangled on some constants as the data_length was pointing into the value.

Changed ConstantSymbol::value to be a Variant

---

src/common.rs
src/omap.rs
src/pe.rs

Implement `fmt::Debug` for `AddressMap`. Also adds a convenience helper to format hex numbers directly via the debug trait, which makes it easier to use that in custom Debug implementations.

Implement Debug for AddressMap

---

examples/stream_names.rs
src/common.rs
src/dbi.rs
src/pdb.rs
src/pdbi.rs

While the MSF stores the stream count as `u32`, it seems to be a general pattern in PDBs to store `u16` stream indices and indicate the absence of a stream with `0xffff`. To abstract this behavior, this PR introduces a transparent `StreamIndex` type.
All code is refactored to use this new type now. As a nice side effect, the access to DBI extra streams is now much smoother. Also, this forces us to check for the absence of streams more consistently when using stream indices internally (e.g. as it was missed for module info streams initially).
The only exception to this seems to be the named stream table, which contains `u32` stream indices. I've decided to make a lossy conversion to a `StreamIndex`, since this is in the public interface. In general, the `StreamNames` type might need a …

Add an explicit type for stream indices

---

src/common.rs

The alignment check in `ParseBuffer` was invalid and might have led to a premature `UnexpectedEof` error.

Fix an invalid check when aligning buffers

---

examples/pdb2hpp.rs
src/common.rs
src/pdb.rs
src/tpi/data.rs
src/tpi/header.rs
src/tpi/id.rs
src/tpi/mod.rs
src/tpi/primitive.rs
tests/type_information.rs

This PR exposes the ID stream (IPI). 
The TPI and IPI streams share the same structure, but they contain different records. Most importantly, the type of index used indicates whether a type lives in the IPI or the TPI. In `microsoft-pdb` this is either `CV_typ_t` for types, or `CV_ItemId` for ids. Of course, both are `u32`.
To create a clear interface that avoids confusion, identifiers are clearly separated into `TypeIndex(u32)` and `IdIndex(u32)`. Since now the id stream needs the same root struct, iterator and finder, this is abstracted into `ItemInformation<I>`, `ItemIter<I>` and `ItemFinder<I>`, where `I` is the index being used. On top of that, there are type definitions to simplify the handling of such types: `type Type<'t> = Item<'t, TypeIndex>`, etc.
Apart from some renaming for …

Implement support for IPI types

---

src/common.rs
src/dbi.rs
src/lib.rs
src/modi/mod.rs
src/symbol/annotations.rs
src/tpi/data.rs
src/tpi/id.rs
src/tpi/primitive.rs

Enables `warn(missing_docs)` for the entire crate to ensure that new interfaces are documented properly. The only exception is `tpi/data.rs` -- too many comments are missing there.

Warn for missing docs of public types

---

examples/pdb2hpp.rs
src/tpi/primitive.rs

This changes the variants of the `Indirection` enum to align with `PointerKind` and also the names used in Microsoft PDB.
Additionally, this fixes a bug when parsing `Huge16` (0x3), which was incorrectly parsed into `Far16` before.

Fix parsing of primitive type indirections

---

src/omap.rs
src/pdb.rs

Some PDBs seem to have no section headers, like for instance .NET Portable PDBs. In this case, `pdb.address_map()` used to return `Error::AddressMapNotFound`. It's slightly more ergonomic to return an empty address map for such a case, so that it can be used in `offset.to_rva(&address_map)` and the likes.
The case where `omap_from_src` and `omap_to_src` are missing is still returned as error, though.

Return an Address map if section headers are missing

---

Cargo.lock
Cargo.toml
src/common.rs
src/modi/c13.rs
src/msf/mod.rs
src/strings.rs

This patch replaces `Pread` derive with manual implementations. It makes the source code a bit bigger, but reduces the compilation time at least by half on my CPU.
Multi-threaded build:
```bash
> cargo clean; cargo build --release
Compiling ...
Finished release [optimized] target(s) in 7.55s
#after
> cargo clean; cargo build --release
Compiling ...
Finished release [optimized] target(s) in 4.26s
```
Single-threaded build:
```bash
> cargo clean; cargo build --release
Compiling ...
Finished release [optimized] target(s) in 32.05s
#after
> cargo clean; cargo build --release
Compiling ...
Finished release [optimized] target(s) in 14.80s
```
Build on CI takes 49.29s instead 58.35s of now. Not sure why the difference is that small.
PS: I understand that this is a controversial patch.

Remove scroll derive.

---

src/msf/mod.rs

Previously `pdb::PDB::open` would return a std::io::Error with ErrorKind
UnexpectedEof for files which were too small to be parsed into a PDB.
This EOF may indeed be a proper EOF if the file is small and therefore
we should return UnrecognizedFileFormat.
Adds a test to verify the behavior added here.
Fixes #75

Return UnrecognizedFileFormat for files too small

---

src/msf/mod.rs

Compiling on rust 1.37.0 gives the following error:
```
error[E0008]: cannot bind by-move into a pattern guard
--> src/msf/mod.rs:393:28
|
393 |             Error::IoError(x) if x.kind() == std::io::ErrorKind::UnexpectedEof => {
|                            ^ moves value into pattern guard
error: aborting due to previous error
```
Modifying the match statement slightly will let rust 1.37.0 as well as 1.40.0 compile the pdb crate successfully.

Fixes compilation on rust 1.37.0

---

src/pdb.rs
src/tpi/header.rs
src/tpi/mod.rs
tests/id_information.rs
tests/omap_address_translation.rs

The ID stream may be completely empty if there are no ids in a PDB. Parsing the header fails in this case with an `UnexpectedEof` error, which is not clean. Instead, we can return an `Option` that explicitly indicates that there is no ID information available.

Handle empty TPI and IPI streams

---

src/modi/c13.rs

Fixes computation of the code length of inlinee line records if they are not declared explicitly in binary annotations. 
In many cases, binary annotations set the code length explicitly using opcodes like `ChangeCodeLengthAndCodeOffset`. In some cases, however, the compiler only advances the code offset using `ChangeCodeOffsetAndLineOffset`. In this case, the code length should be inferred by the difference from the last line record. 
The initial implementation wrongly subtracted the code offset base instead of the last offset. In this patch, the last offset is correctly subtracted.
Fixes #78

Fix invalid C13 inlinee line length

---

src/common.rs

With Rust 1.42.0, `Error::description` was deprecated. Since the `Display` implementation contains more information, it is sort-of duplicate anyway. This also implements `Error::source`.

Remove deprecated Error::description and add source

---

Cargo.lock
Cargo.toml
src/common.rs
src/modi/c13.rs
src/msf/mod.rs
src/strings.rs
src/symbol/constants.rs
src/symbol/mod.rs
src/tpi/id.rs
tests/omap_address_translation.rs

Breaking change: `fallible-iterator` is updated to 0.2.0, which is now more widely used.
Also updates `uuid` and `scoll` internally.

Update fallible-iterator and other dependencies

---

src/common.rs

It was incorrectly pointing to `rva` instead of `to_rva`.

Fix method name in PdbInternalSectionOffset documentation

---

src/symbol/mod.rs

This change makes fields of the `CompileFlags` struct public so they can be read outside of this crate. See #89.

Make CompileFlags fields public

---

src/dbi.rs
src/symbol/constants.rs
src/symbol/mod.rs

This change allows rustdoc to index `CPUType` and `SourceLanguage` types (see #89 for more info). While I was examining the rustdoc output I noticed that there were a few URLs not properly hyperlinked, so I fixed those aswell.

Re-export public enums located in private `constants` crate

---

src/omap.rs
src/pe.rs
tests/omap_address_translation.rs

Section 0 isn't a real section, but it appears in real PDBs. Right now we panic when we should just return `None`. Fixes #87.

Disregard section zero when performing OMAP translation

---

.travis.yml
src/common.rs
src/dbi.rs
src/framedata.rs
src/lib.rs
src/modi/c13.rs
src/modi/mod.rs
src/omap.rs
src/pdb.rs
src/pdbi.rs
src/source.rs
src/strings.rs
src/symbol/mod.rs
src/tpi/id.rs
src/tpi/mod.rs
src/tpi/primitive.rs

With intra doc links having landed on stable and enabled by default on docs.rs,
we can now adopt intra doc links across the code base in favor of direct links
to HTML pages. This also uncovered a number of broken links that have been fixed
now.
I've added an additional Travis job to verify that all links are valid.

Adopt intra doc links and fix broken docs

---

src/common.rs
src/framedata.rs
src/modi/c13.rs
src/modi/mod.rs
src/msf/mod.rs
src/msf/page_list.rs
src/omap.rs
src/source.rs
src/symbol/annotations.rs
src/tpi/data.rs
src/tpi/id.rs
tests/symbol_table.rs

This is currently breaking on master.
The only functional change is that the `SourceView` trait no longer requires `Drop`. See [`drop_bounds`](https://doc.rust-lang.org/nightly/rustc/lints/listing/warn-by-default.html#drop-bounds) for more arguments why this is not needed.

Fix Rust 1.49 clippy lints and Edition 2018 idioms

---

src/common.rs
src/dbi.rs
src/symbol/constants.rs
src/symbol/mod.rs
src/tpi/data.rs
src/tpi/id.rs
src/tpi/primitive.rs

Some of our types - especially enumerations - are either known to be extensible, incomplete, or not meant to be matched exhaustively. This PR adds `#[non-exhaustive]` annotations to these types to allow changing them in upcoming versions without breaking the API.
Fixes https://github.com/willglynn/pdb/issues/94

Mark certain types as non_exhaustive

---

src/modi/mod.rs
src/pdb.rs

The expected CV Signature of a ModuleInfo seems to be a part of the
symbols, meaning that we shouldn’t read it when the symbols_size is 0.

fix: Allow parsing modules that have no symbols

---

src/dbi.rs

I was referencing this project to figure out pdb format, and I think this calculation is wrong, although `mfc_type_server_index` looks to be 0 in pdb's which may be why its went unnoticed, going off of <https://llvm.org/docs/PDB/DbiStream.html> there should only be 6 substream sizes, and the index should be irrelevant

Fix DBIExtraStreams offset calculation

---

src/msf/page_list.rs

I just hit this overflow while running the crate through a fuzzer.

fix: Avoid arithmetic overflow in PageList::push

---

src/common.rs

I was trying to figure out how cross module reference work again and came across that the user of the crate needs to manually handle the casing here. We do however not document this currently and this is easy to miss. Added a note to the place where I figured it might be most likely read.

Added note on case insensitivity of cross module refs

---

src/tpi/data.rs

I encountered a PDB which contained a type looking something like this:
```rust
ClassType {
kind: Struct,
count: 0x10,
properties: TypeProperties(
0x200,
),
fields: Some(
TypeIndex(0x5326),
),
derived_from: None,
vtable_shape: None,
size: 0x5D00,
name: RawString("_REDACTED_DATA"),
unique_name: Some(
RawString(".?AU_REDACTED_DATA@@"),
),
}
```
I noticed something weird about all structs containing this one: all of them had incorrect field offsets (calculated by me) and incorrect sizes. Upon further observation I noticed that the `size` had been truncated from `0xF5D00` to `0x5D00`. This patch removes the integer truncation from classes/structs (tested) and from unions (untested) and changes their types to be `u64`.

Retain u64 size for class and union sizes

---

examples/pdb2hpp.rs
examples/pdb_framedata.rs
examples/pdb_lines.rs
examples/pdb_symbols.rs
src/common.rs
src/dbi.rs
src/modi/c13.rs
src/msf/mod.rs
src/pdb.rs
src/pdbi.rs
src/pe.rs
src/strings.rs
src/symbol/mod.rs
src/tpi/data.rs
src/tpi/primitive.rs
tests/pdb_lines.rs

Time has passed and clippy as evolved. This PR fixes lints, mostly
applying the auto-fixer. We're also compatible with edition 2021 now,
most notably by supplying a format string to `panic!` in all cases.
Note that this contains a breaking change: `MSF` has been renamed to
`Msf`. I expect minimal breakage in actual users of this crate, since
this probably doesn't need to be implemented manually.
There are still many `dead_code` warnings remaining that I want to take
a closer look at.

Fix lints and idioms

---

src/symbol/constants.rs

I got these from https://llvm.org/docs/PDB/CodeViewSymbols.html#s-fastlink-0x1167 .
There's a PDB file in https://github.com/mstange/pdb-addr2line/issues/52#issuecomment-1130225425 which uses S_FASTLINK.

Add two missing symbol type constants.

---

examples/pdb_lines.rs
src/modi/c13.rs
src/modi/mod.rs

`ProcedureSymbol` records for MASM functions have code ranges associated that do not match the actual code or line records. 
`lines_at_offset` assumed that if there is a lines subsection for a symbol, it shares the exact same start offset as the symbol. However, this is not the case for MASM functions, where the symbol's offset can lie *after* the actual start of the instructions / line records. Since the name of `lines_at_offset` was chosen badly, it is now renamed to `lines_for_symbol`, and explicitly states that it may return line records **outside** of the symbol's stated code range.
A consumer of this should probably collect the line records for each symbol and infer a proper code range.
Also, the internal implementation of `lines_at_offset` was slow in two regards: It had linear …

Fix lines for MASM symbols

---

src/dbi.rs
src/pe.rs

`SectionCharacteristics` is implemented as a public newtype around the raw
`u32`, giving access to the inner value in case flags are not implemented. The
wrapper follows the same pattern used for flags in the TPI, which parses the
flag values lazily.
There is special handling for the mutually exclusive alignment values, as well
as the `_NO_PAD` flag. Otherwise, all flags are exposed directly as booleans.
Fixes https://github.com/willglynn/pdb/issues/106

Add typing for ImageSectionHeader::characteristics

---

.codecov.yml
.craft.yml
.editorconfig
.github/workflows/ci.yml
.github/workflows/enforce-license-compliance.yml
.github/workflows/release.yml
.github/workflows/weekly.yml
.gitignore
scripts/bump-version.sh

This pretty much copy-pastes the "newest" version of the generic CI workflow running the various tests, code coverage, etc.
It also adds the Sentry standard release workflow and craft definitions as well.
NOTE to self: I need to add this to `publish` as well to have it auto-approved.

Update CI and add a Release workflow

---

.semgrepignore

Ignores the `examples/` and `tests/` directories (along with anything in `.gitignore`) to reduce finding noise.

chore: setup semgrepignore
